# Site settings
title: Qubes OS Project
description: "Qubes OS is an open source operating system designed to provide strong security for desktop computing using Security by Compartmentalization approach. Qubes is based on Xen, X Window System, and Linux, and can run most Linux applications and utilize most of the Linux drivers. It can also run Windows apps natively in Windows AppVMs (Beta)."
repository: "https://github.com/Nukama/nukama.github.io"
help_url: "https://github.com/Nukama/nukama.github.io/wiki"

# Project Settings
project_url: "https://www.qubes-os.org"
project_repo_path: "https://github.com/QubesOS"
project_repo_site: "/qubesos.github.io"
project_repo_artwork: "/qubes-artwork"

# Build settings
timezone: UTC
encoding: utf-8
markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
gems:
  - jekyll-redirect-from

collections:
  docs:
    output: true
  wiki:
    output: true
  hcl:
    output: true
  author:
    output: true
