# Site settings
title: Qubes OS Project
description: "Qubes OS - Secure open-source desktop operating system"
url: "https://nukama.github.io"
repository: "https://github.com/Nukama/nukama.github.io"
help_url: "https://github.com/Nukama/nukama.github.io/wiki"

# Build settings
timezone: UTC
encoding: utf-8
markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

collections:
#  docs:
#    output: true
  wiki:
    output: true

#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default"
#  -
#    scope:
#      path: "posts/rootkovska" # an empty string here means all files in the project
#    values:
#      layout: "news"
